<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
    <link rel="stylesheet" href="css/main.css">
</head>
<body>
    <h1 class="text-center">Formulaire</h1>
    
    <main class="container">
        <form action="admin.php" method="post">
            <div class="form-group">
                <label for="username">Nom d'utilisateur</label>
                <input name="username" id="username" type="text" require>
            </div>
            <div class="form-group">
                <label for="password">Mot de passe</label>
                <input name="password" id="password" type="password" require>
            </div>
            <button class="button button-primary">Envoyer</button>
        </form>
    </main>
</body>
</html>